name: GitHub Pages
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: latest
          run_install: true

      - name: Setup wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'

      - name: Build Okkhor
        run: wasm-pack build ./okkhor --target web

      - name: Vite Build
        run: pnpm vite build --base=/avro-slate/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
